/**
 * Unified language list supporting:
 * - name / nativeName: native name of the language
 * - nameEn: name in English
 * - nameFr: name in French (for French-speaking users)
 */
export interface Language {
  code: string;
  name: string;       // native name
  nativeName: string; // alias for name (review generator compat)
  nameEn: string;     // name in English
  nameFr: string;     // name in French
}

export const LANGUAGES: Language[] = [
  { code: "af",    name: "Afrikaans",            nativeName: "Afrikaans",            nameEn: "Afrikaans",                 nameFr: "Afrikaans" },
  { code: "sq",    name: "Shqip",                nativeName: "Shqip",                nameEn: "Albanian",                  nameFr: "Albanais" },
  { code: "am",    name: "አማርኛ",                 nativeName: "አማርኛ",                 nameEn: "Amharic",                   nameFr: "Amharique" },
  { code: "ar",    name: "العربية",               nativeName: "العربية",               nameEn: "Arabic",                    nameFr: "Arabe" },
  { code: "hy",    name: "Հայերեն",               nativeName: "Հայերեն",               nameEn: "Armenian",                  nameFr: "Arménien" },
  { code: "az",    name: "Azərbaycan dili",       nativeName: "Azərbaycan dili",       nameEn: "Azerbaijani",               nameFr: "Azerbaïdjanais" },
  { code: "eu",    name: "Euskara",               nativeName: "Euskara",               nameEn: "Basque",                    nameFr: "Basque" },
  { code: "be",    name: "Беларуская",            nativeName: "Беларуская",            nameEn: "Belarusian",                nameFr: "Biélorusse" },
  { code: "bn",    name: "বাংলা",                 nativeName: "বাংলা",                 nameEn: "Bengali",                   nameFr: "Bengali" },
  { code: "bs",    name: "Bosanski",              nativeName: "Bosanski",              nameEn: "Bosnian",                   nameFr: "Bosniaque" },
  { code: "bg",    name: "Български",             nativeName: "Български",             nameEn: "Bulgarian",                 nameFr: "Bulgare" },
  { code: "my",    name: "မြန်မာဘာသာ",            nativeName: "မြန်မာဘာသာ",            nameEn: "Burmese",                   nameFr: "Birman" },
  { code: "ca",    name: "Català",                nativeName: "Català",                nameEn: "Catalan",                   nameFr: "Catalan" },
  { code: "ceb",   name: "Cebuano",               nativeName: "Cebuano",               nameEn: "Cebuano",                   nameFr: "Cebuano" },
  { code: "zh",    name: "中文 (简体)",             nativeName: "中文",                  nameEn: "Chinese (Simplified)",      nameFr: "Chinois (simplifié)" },
  { code: "zh-TW", name: "中文 (繁體)",             nativeName: "中文 (繁體)",             nameEn: "Chinese (Traditional)",     nameFr: "Chinois (traditionnel)" },
  { code: "hr",    name: "Hrvatski",              nativeName: "Hrvatski",              nameEn: "Croatian",                  nameFr: "Croate" },
  { code: "cs",    name: "Čeština",               nativeName: "Čeština",               nameEn: "Czech",                     nameFr: "Tchèque" },
  { code: "da",    name: "Dansk",                 nativeName: "Dansk",                 nameEn: "Danish",                    nameFr: "Danois" },
  { code: "nl",    name: "Nederlands",            nativeName: "Nederlands",            nameEn: "Dutch",                     nameFr: "Néerlandais" },
  { code: "en",    name: "English",               nativeName: "English",               nameEn: "English",                   nameFr: "Anglais" },
  { code: "eo",    name: "Esperanto",             nativeName: "Esperanto",             nameEn: "Esperanto",                 nameFr: "Espéranto" },
  { code: "et",    name: "Eesti",                 nativeName: "Eesti",                 nameEn: "Estonian",                  nameFr: "Estonien" },
  { code: "fi",    name: "Suomi",                 nativeName: "Suomi",                 nameEn: "Finnish",                   nameFr: "Finnois" },
  { code: "fr",    name: "Français",              nativeName: "Français",              nameEn: "French",                    nameFr: "Français" },
  { code: "gl",    name: "Galego",                nativeName: "Galego",                nameEn: "Galician",                  nameFr: "Galicien" },
  { code: "ka",    name: "ქართული",               nativeName: "ქართული",               nameEn: "Georgian",                  nameFr: "Géorgien" },
  { code: "de",    name: "Deutsch",               nativeName: "Deutsch",               nameEn: "German",                    nameFr: "Allemand" },
  { code: "el",    name: "Ελληνικά",              nativeName: "Ελληνικά",              nameEn: "Greek",                     nameFr: "Grec" },
  { code: "gu",    name: "ગુજરાતી",               nativeName: "ગુજરાતી",               nameEn: "Gujarati",                  nameFr: "Gujarati" },
  { code: "ht",    name: "Kreyòl ayisyen",        nativeName: "Kreyòl ayisyen",        nameEn: "Haitian Creole",            nameFr: "Créole haïtien" },
  { code: "ha",    name: "Hausa",                 nativeName: "Hausa",                 nameEn: "Hausa",                     nameFr: "Haoussa" },
  { code: "he",    name: "עברית",                 nativeName: "עברית",                 nameEn: "Hebrew",                    nameFr: "Hébreu" },
  { code: "hi",    name: "हिन्दी",                nativeName: "हिन्दी",                nameEn: "Hindi",                     nameFr: "Hindi" },
  { code: "hu",    name: "Magyar",                nativeName: "Magyar",                nameEn: "Hungarian",                 nameFr: "Hongrois" },
  { code: "is",    name: "Íslenska",              nativeName: "Íslenska",              nameEn: "Icelandic",                 nameFr: "Islandais" },
  { code: "ig",    name: "Igbo",                  nativeName: "Igbo",                  nameEn: "Igbo",                      nameFr: "Igbo" },
  { code: "id",    name: "Bahasa Indonesia",      nativeName: "Bahasa Indonesia",      nameEn: "Indonesian",                nameFr: "Indonésien" },
  { code: "ga",    name: "Gaeilge",               nativeName: "Gaeilge",               nameEn: "Irish",                     nameFr: "Irlandais" },
  { code: "it",    name: "Italiano",              nativeName: "Italiano",              nameEn: "Italian",                   nameFr: "Italien" },
  { code: "ja",    name: "日本語",                 nativeName: "日本語",                 nameEn: "Japanese",                  nameFr: "Japonais" },
  { code: "jv",    name: "Basa Jawa",             nativeName: "Basa Jawa",             nameEn: "Javanese",                  nameFr: "Javanais" },
  { code: "kn",    name: "ಕನ್ನಡ",                 nativeName: "ಕನ್ನಡ",                 nameEn: "Kannada",                   nameFr: "Kannada" },
  { code: "kk",    name: "Қазақша",               nativeName: "Қазақша",               nameEn: "Kazakh",                    nameFr: "Kazakh" },
  { code: "km",    name: "ខ្មែរ",                  nativeName: "ខ្មែរ",                  nameEn: "Khmer",                     nameFr: "Khmer" },
  { code: "rw",    name: "Kinyarwanda",           nativeName: "Kinyarwanda",           nameEn: "Kinyarwanda",               nameFr: "Kinyarwanda" },
  { code: "ko",    name: "한국어",                 nativeName: "한국어",                 nameEn: "Korean",                    nameFr: "Coréen" },
  { code: "ku",    name: "Kurdi",                 nativeName: "Kurdi",                 nameEn: "Kurdish",                   nameFr: "Kurde" },
  { code: "ky",    name: "Кыргызча",              nativeName: "Кыргызча",              nameEn: "Kyrgyz",                    nameFr: "Kirghiz" },
  { code: "lo",    name: "ລາວ",                   nativeName: "ລາວ",                   nameEn: "Lao",                       nameFr: "Laotien" },
  { code: "lv",    name: "Latviešu",              nativeName: "Latviešu",              nameEn: "Latvian",                   nameFr: "Letton" },
  { code: "lt",    name: "Lietuvių",              nativeName: "Lietuvių",              nameEn: "Lithuanian",                nameFr: "Lituanien" },
  { code: "lb",    name: "Lëtzebuergesch",        nativeName: "Lëtzebuergesch",        nameEn: "Luxembourgish",             nameFr: "Luxembourgeois" },
  { code: "mk",    name: "Македонски",            nativeName: "Македонски",            nameEn: "Macedonian",                nameFr: "Macédonien" },
  { code: "mg",    name: "Malagasy",              nativeName: "Malagasy",              nameEn: "Malagasy",                  nameFr: "Malgache" },
  { code: "ms",    name: "Bahasa Melayu",         nativeName: "Bahasa Melayu",         nameEn: "Malay",                     nameFr: "Malais" },
  { code: "ml",    name: "മലയാളം",                nativeName: "മലയാളം",                nameEn: "Malayalam",                 nameFr: "Malayalam" },
  { code: "mt",    name: "Malti",                 nativeName: "Malti",                 nameEn: "Maltese",                   nameFr: "Maltais" },
  { code: "mi",    name: "Te Reo Maori",          nativeName: "Te Reo Maori",          nameEn: "Maori",                     nameFr: "Maori" },
  { code: "mr",    name: "मराठी",                 nativeName: "मराठी",                 nameEn: "Marathi",                   nameFr: "Marathi" },
  { code: "mn",    name: "Монгол",                nativeName: "Монгол",                nameEn: "Mongolian",                 nameFr: "Mongol" },
  { code: "ne",    name: "नेपाली",                nativeName: "नेपाली",                nameEn: "Nepali",                    nameFr: "Népalais" },
  { code: "no",    name: "Norsk",                 nativeName: "Norsk",                 nameEn: "Norwegian",                 nameFr: "Norvégien" },
  { code: "ps",    name: "پښتو",                  nativeName: "پښتو",                  nameEn: "Pashto",                    nameFr: "Pachto" },
  { code: "fa",    name: "فارسی",                 nativeName: "فارسی",                 nameEn: "Persian",                   nameFr: "Persan" },
  { code: "pl",    name: "Polski",                nativeName: "Polski",                nameEn: "Polish",                    nameFr: "Polonais" },
  { code: "pt",    name: "Português",             nativeName: "Português",             nameEn: "Portuguese",                nameFr: "Portugais" },
  { code: "pt-BR", name: "Português (Brasil)",    nativeName: "Português (Brasil)",    nameEn: "Portuguese (Brazil)",       nameFr: "Portugais (Brésil)" },
  { code: "pa",    name: "ਪੰਜਾਬੀ",                nativeName: "ਪੰਜਾਬੀ",                nameEn: "Punjabi",                   nameFr: "Pendjabi" },
  { code: "ro",    name: "Română",                nativeName: "Română",                nameEn: "Romanian",                  nameFr: "Roumain" },
  { code: "ru",    name: "Русский",               nativeName: "Русский",               nameEn: "Russian",                   nameFr: "Russe" },
  { code: "sm",    name: "Gagana Samoa",          nativeName: "Gagana Samoa",          nameEn: "Samoan",                    nameFr: "Samoan" },
  { code: "gd",    name: "Gàidhlig",              nativeName: "Gàidhlig",              nameEn: "Scottish Gaelic",           nameFr: "Gaélique écossais" },
  { code: "sr",    name: "Српски",                nativeName: "Српски",                nameEn: "Serbian",                   nameFr: "Serbe" },
  { code: "sn",    name: "Shona",                 nativeName: "Shona",                 nameEn: "Shona",                     nameFr: "Shona" },
  { code: "si",    name: "සිංහල",                 nativeName: "සිංහල",                 nameEn: "Sinhala",                   nameFr: "Cingalais" },
  { code: "sk",    name: "Slovenčina",            nativeName: "Slovenčina",            nameEn: "Slovak",                    nameFr: "Slovaque" },
  { code: "sl",    name: "Slovenščina",           nativeName: "Slovenščina",           nameEn: "Slovenian",                 nameFr: "Slovène" },
  { code: "so",    name: "Soomaali",              nativeName: "Soomaali",              nameEn: "Somali",                    nameFr: "Somali" },
  { code: "es",    name: "Español",               nativeName: "Español",               nameEn: "Spanish",                   nameFr: "Espagnol" },
  { code: "su",    name: "Basa Sunda",            nativeName: "Basa Sunda",            nameEn: "Sundanese",                 nameFr: "Soundanais" },
  { code: "sw",    name: "Kiswahili",             nativeName: "Kiswahili",             nameEn: "Swahili",                   nameFr: "Swahili" },
  { code: "sv",    name: "Svenska",               nativeName: "Svenska",               nameEn: "Swedish",                   nameFr: "Suédois" },
  { code: "tl",    name: "Tagalog",               nativeName: "Tagalog",               nameEn: "Tagalog",                   nameFr: "Tagalog" },
  { code: "tg",    name: "Тоҷикӣ",                nativeName: "Тоҷикӣ",                nameEn: "Tajik",                     nameFr: "Tadjik" },
  { code: "ta",    name: "தமிழ்",                 nativeName: "தமிழ்",                 nameEn: "Tamil",                     nameFr: "Tamoul" },
  { code: "te",    name: "తెలుగు",                nativeName: "తెలుగు",                nameEn: "Telugu",                    nameFr: "Télougou" },
  { code: "th",    name: "ภาษาไทย",               nativeName: "ภาษาไทย",               nameEn: "Thai",                      nameFr: "Thaï" },
  { code: "ti",    name: "ትግርኛ",                  nativeName: "ትግርኛ",                  nameEn: "Tigrinya",                  nameFr: "Tigrigna" },
  { code: "tr",    name: "Türkçe",                nativeName: "Türkçe",                nameEn: "Turkish",                   nameFr: "Turc" },
  { code: "tk",    name: "Türkmen",               nativeName: "Türkmen",               nameEn: "Turkmen",                   nameFr: "Turkmène" },
  { code: "uk",    name: "Українська",            nativeName: "Українська",            nameEn: "Ukrainian",                 nameFr: "Ukrainien" },
  { code: "ur",    name: "اردو",                  nativeName: "اردو",                  nameEn: "Urdu",                      nameFr: "Ourdou" },
  { code: "ug",    name: "ئۇيغۇرچە",             nativeName: "ئۇيغۇرچە",             nameEn: "Uyghur",                    nameFr: "Ouïghour" },
  { code: "uz",    name: "Oʻzbekcha",             nativeName: "Oʻzbekcha",             nameEn: "Uzbek",                     nameFr: "Ouzbek" },
  { code: "vi",    name: "Tiếng Việt",            nativeName: "Tiếng Việt",            nameEn: "Vietnamese",                nameFr: "Vietnamien" },
  { code: "cy",    name: "Cymraeg",               nativeName: "Cymraeg",               nameEn: "Welsh",                     nameFr: "Gallois" },
  { code: "xh",    name: "isiXhosa",              nativeName: "isiXhosa",              nameEn: "Xhosa",                     nameFr: "Xhosa" },
  { code: "yi",    name: "ייִדיש",                nativeName: "ייִדיש",                nameEn: "Yiddish",                   nameFr: "Yiddish" },
  { code: "yo",    name: "Yorùbá",                nativeName: "Yorùbá",                nameEn: "Yoruba",                    nameFr: "Yoruba" },
  { code: "zu",    name: "isiZulu",               nativeName: "isiZulu",               nameEn: "Zulu",                      nameFr: "Zoulou" },
  { code: "ln",    name: "Lingála",               nativeName: "Lingála",               nameEn: "Lingala",                   nameFr: "Lingala" },
  { code: "wo",    name: "Wolof",                 nativeName: "Wolof",                 nameEn: "Wolof",                     nameFr: "Wolof" },
  { code: "fo",    name: "Føroyskt",              nativeName: "Føroyskt",              nameEn: "Faroese",                   nameFr: "Féroïen" },
];
