/**
 * Unified language list supporting both:
 * - nativeName: used by review generator components (SettingsForm, MultiProductForm)
 * - nameEn: used by theme customizer components (store-config-form)
 */
export interface Language {
  code: string;
  name: string;       // name in the language itself (native name)
  nativeName: string; // alias for name (review generator compat)
  nameEn: string;     // name in English (theme customizer compat)
}

export const LANGUAGES: Language[] = [
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans", nameEn: "Afrikaans" },
  { code: "sq", name: "Shqip", nativeName: "Shqip", nameEn: "Albanian" },
  { code: "am", name: "አማርኛ", nativeName: "አማርኛ", nameEn: "Amharic" },
  { code: "ar", name: "العربية", nativeName: "العربية", nameEn: "Arabic" },
  { code: "hy", name: "Հայերեն", nativeName: "Հայերեն", nameEn: "Armenian" },
  { code: "az", name: "Azərbaycan dili", nativeName: "Azərbaycan dili", nameEn: "Azerbaijani" },
  { code: "eu", name: "Euskara", nativeName: "Euskara", nameEn: "Basque" },
  { code: "be", name: "Беларуская", nativeName: "Беларуская", nameEn: "Belarusian" },
  { code: "bn", name: "বাংলা", nativeName: "বাংলা", nameEn: "Bengali" },
  { code: "bs", name: "Bosanski", nativeName: "Bosanski", nameEn: "Bosnian" },
  { code: "bg", name: "Български", nativeName: "Български", nameEn: "Bulgarian" },
  { code: "my", name: "မြန်မာဘာသာ", nativeName: "မြန်မာဘာသာ", nameEn: "Burmese" },
  { code: "ca", name: "Català", nativeName: "Català", nameEn: "Catalan" },
  { code: "ceb", name: "Cebuano", nativeName: "Cebuano", nameEn: "Cebuano" },
  { code: "zh", name: "中文 (简体)", nativeName: "中文", nameEn: "Chinese (Simplified)" },
  { code: "zh-TW", name: "中文 (繁體)", nativeName: "中文 (繁體)", nameEn: "Chinese (Traditional)" },
  { code: "hr", name: "Hrvatski", nativeName: "Hrvatski", nameEn: "Croatian" },
  { code: "cs", name: "Čeština", nativeName: "Čeština", nameEn: "Czech" },
  { code: "da", name: "Dansk", nativeName: "Dansk", nameEn: "Danish" },
  { code: "nl", name: "Nederlands", nativeName: "Nederlands", nameEn: "Dutch" },
  { code: "en", name: "English", nativeName: "English", nameEn: "English" },
  { code: "eo", name: "Esperanto", nativeName: "Esperanto", nameEn: "Esperanto" },
  { code: "et", name: "Eesti", nativeName: "Eesti", nameEn: "Estonian" },
  { code: "fi", name: "Suomi", nativeName: "Suomi", nameEn: "Finnish" },
  { code: "fr", name: "Français", nativeName: "Français", nameEn: "French" },
  { code: "gl", name: "Galego", nativeName: "Galego", nameEn: "Galician" },
  { code: "ka", name: "ქართული", nativeName: "ქართული", nameEn: "Georgian" },
  { code: "de", name: "Deutsch", nativeName: "Deutsch", nameEn: "German" },
  { code: "el", name: "Ελληνικά", nativeName: "Ελληνικά", nameEn: "Greek" },
  { code: "gu", name: "ગુજરાતી", nativeName: "ગુજરાતી", nameEn: "Gujarati" },
  { code: "ht", name: "Kreyòl ayisyen", nativeName: "Kreyòl ayisyen", nameEn: "Haitian Creole" },
  { code: "ha", name: "Hausa", nativeName: "Hausa", nameEn: "Hausa" },
  { code: "he", name: "עברית", nativeName: "עברית", nameEn: "Hebrew" },
  { code: "hi", name: "हिन्दी", nativeName: "हिन्दी", nameEn: "Hindi" },
  { code: "hu", name: "Magyar", nativeName: "Magyar", nameEn: "Hungarian" },
  { code: "is", name: "Íslenska", nativeName: "Íslenska", nameEn: "Icelandic" },
  { code: "ig", name: "Igbo", nativeName: "Igbo", nameEn: "Igbo" },
  { code: "id", name: "Bahasa Indonesia", nativeName: "Bahasa Indonesia", nameEn: "Indonesian" },
  { code: "ga", name: "Gaeilge", nativeName: "Gaeilge", nameEn: "Irish" },
  { code: "it", name: "Italiano", nativeName: "Italiano", nameEn: "Italian" },
  { code: "ja", name: "日本語", nativeName: "日本語", nameEn: "Japanese" },
  { code: "jv", name: "Basa Jawa", nativeName: "Basa Jawa", nameEn: "Javanese" },
  { code: "kn", name: "ಕನ್ನಡ", nativeName: "ಕನ್ನಡ", nameEn: "Kannada" },
  { code: "kk", name: "Қазақша", nativeName: "Қазақша", nameEn: "Kazakh" },
  { code: "km", name: "ខ្មែរ", nativeName: "ខ្មែរ", nameEn: "Khmer" },
  { code: "rw", name: "Kinyarwanda", nativeName: "Kinyarwanda", nameEn: "Kinyarwanda" },
  { code: "ko", name: "한국어", nativeName: "한국어", nameEn: "Korean" },
  { code: "ku", name: "Kurdi", nativeName: "Kurdi", nameEn: "Kurdish" },
  { code: "ky", name: "Кыргызча", nativeName: "Кыргызча", nameEn: "Kyrgyz" },
  { code: "lo", name: "ລາວ", nativeName: "ລາວ", nameEn: "Lao" },
  { code: "lv", name: "Latviešu", nativeName: "Latviešu", nameEn: "Latvian" },
  { code: "lt", name: "Lietuvių", nativeName: "Lietuvių", nameEn: "Lithuanian" },
  { code: "lb", name: "Lëtzebuergesch", nativeName: "Lëtzebuergesch", nameEn: "Luxembourgish" },
  { code: "mk", name: "Македонски", nativeName: "Македонски", nameEn: "Macedonian" },
  { code: "mg", name: "Malagasy", nativeName: "Malagasy", nameEn: "Malagasy" },
  { code: "ms", name: "Bahasa Melayu", nativeName: "Bahasa Melayu", nameEn: "Malay" },
  { code: "ml", name: "മലയാളം", nativeName: "മലയാളം", nameEn: "Malayalam" },
  { code: "mt", name: "Malti", nativeName: "Malti", nameEn: "Maltese" },
  { code: "mi", name: "Te Reo Maori", nativeName: "Te Reo Maori", nameEn: "Maori" },
  { code: "mr", name: "मराठी", nativeName: "मराठी", nameEn: "Marathi" },
  { code: "mn", name: "Монгол", nativeName: "Монгол", nameEn: "Mongolian" },
  { code: "ne", name: "नेपाली", nativeName: "नेपाली", nameEn: "Nepali" },
  { code: "no", name: "Norsk", nativeName: "Norsk", nameEn: "Norwegian" },
  { code: "ps", name: "پښتو", nativeName: "پښتو", nameEn: "Pashto" },
  { code: "fa", name: "فارسی", nativeName: "فارسی", nameEn: "Persian" },
  { code: "pl", name: "Polski", nativeName: "Polski", nameEn: "Polish" },
  { code: "pt", name: "Português", nativeName: "Português", nameEn: "Portuguese" },
  { code: "pt-BR", name: "Português (Brasil)", nativeName: "Português (Brasil)", nameEn: "Portuguese (Brazil)" },
  { code: "pa", name: "ਪੰਜਾਬੀ", nativeName: "ਪੰਜਾਬੀ", nameEn: "Punjabi" },
  { code: "ro", name: "Română", nativeName: "Română", nameEn: "Romanian" },
  { code: "ru", name: "Русский", nativeName: "Русский", nameEn: "Russian" },
  { code: "sm", name: "Gagana Samoa", nativeName: "Gagana Samoa", nameEn: "Samoan" },
  { code: "gd", name: "Gàidhlig", nativeName: "Gàidhlig", nameEn: "Scottish Gaelic" },
  { code: "sr", name: "Српски", nativeName: "Српски", nameEn: "Serbian" },
  { code: "sn", name: "Shona", nativeName: "Shona", nameEn: "Shona" },
  { code: "si", name: "සිංහල", nativeName: "සිංහල", nameEn: "Sinhala" },
  { code: "sk", name: "Slovenčina", nativeName: "Slovenčina", nameEn: "Slovak" },
  { code: "sl", name: "Slovenščina", nativeName: "Slovenščina", nameEn: "Slovenian" },
  { code: "so", name: "Soomaali", nativeName: "Soomaali", nameEn: "Somali" },
  { code: "es", name: "Español", nativeName: "Español", nameEn: "Spanish" },
  { code: "su", name: "Basa Sunda", nativeName: "Basa Sunda", nameEn: "Sundanese" },
  { code: "sw", name: "Kiswahili", nativeName: "Kiswahili", nameEn: "Swahili" },
  { code: "sv", name: "Svenska", nativeName: "Svenska", nameEn: "Swedish" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog", nameEn: "Tagalog" },
  { code: "tg", name: "Тоҷикӣ", nativeName: "Тоҷикӣ", nameEn: "Tajik" },
  { code: "ta", name: "தமிழ்", nativeName: "தமிழ்", nameEn: "Tamil" },
  { code: "te", name: "తెలుగు", nativeName: "తెలుగు", nameEn: "Telugu" },
  { code: "th", name: "ภาษาไทย", nativeName: "ภาษาไทย", nameEn: "Thai" },
  { code: "ti", name: "ትግርኛ", nativeName: "ትግርኛ", nameEn: "Tigrinya" },
  { code: "tr", name: "Türkçe", nativeName: "Türkçe", nameEn: "Turkish" },
  { code: "tk", name: "Türkmen", nativeName: "Türkmen", nameEn: "Turkmen" },
  { code: "uk", name: "Українська", nativeName: "Українська", nameEn: "Ukrainian" },
  { code: "ur", name: "اردو", nativeName: "اردو", nameEn: "Urdu" },
  { code: "ug", name: "ئۇيغۇرچە", nativeName: "ئۇيغۇرچە", nameEn: "Uyghur" },
  { code: "uz", name: "Oʻzbekcha", nativeName: "Oʻzbekcha", nameEn: "Uzbek" },
  { code: "vi", name: "Tiếng Việt", nativeName: "Tiếng Việt", nameEn: "Vietnamese" },
  { code: "cy", name: "Cymraeg", nativeName: "Cymraeg", nameEn: "Welsh" },
  { code: "xh", name: "isiXhosa", nativeName: "isiXhosa", nameEn: "Xhosa" },
  { code: "yi", name: "ייִדיש", nativeName: "ייִדיש", nameEn: "Yiddish" },
  { code: "yo", name: "Yorùbá", nativeName: "Yorùbá", nameEn: "Yoruba" },
  { code: "zu", name: "isiZulu", nativeName: "isiZulu", nameEn: "Zulu" },
  { code: "ln", name: "Lingála", nativeName: "Lingála", nameEn: "Lingala" },
  { code: "wo", name: "Wolof", nativeName: "Wolof", nameEn: "Wolof" },
  { code: "fo", name: "Føroyskt", nativeName: "Føroyskt", nameEn: "Faroese" },
];
